### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by mlazaratos** [DZD-eV-Diabetes-Research/meta-kegg-web-wrapper#10]
@motey 

There seems to be an error: [Errno 2] No such file or directory

File "/usr/local/lib/python3.11/site-packages/metaKEGG/modules/pipeline_async.py", line 118, in single_input_genes
entry_dir = os.getcwd()
^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory

I ran one pipeline today, and after that I started getting the error.

I made a fresh conda env with python 3.11.0 and had to addiionally install fsspec

pip install fsspec==2024.10.0

Could you patch that on your end and let me know?

I am preparing the metaKEGG patch version in the meantime

**Comment by motey** [comment]
This is an error in MetaKegg. I dont know what https://github.com/dife-bioinformatics/metaKEGG/blob/master/src/metaKEGG/modules/pipeline_async.py#L118 achieves and why it fails...

**Comment by mlazaratos** [comment]
@motey the patch for metaKEGG under version 1.0.1

https://pypi.org/project/metaKEGG/
https://github.com/dife-bioinformatics/metaKEGG/releases/tag/v1.0.1

Can we try to rebuild the wrapper with this?

**Comment by mlazaratos** [comment]
@motey Thank you for the swift implementation!

Could we display the new default values

1. methylation_genes_column: str = "methylation_gene_symbol"
2. methylation_probe_column: str = "CG_ID"
3. miRNA_genes_column: str = "miRNA_gene_symbol"
4. miRNA_ID_column: str = "miRNA_ID"

Functions affected: 

methylated_genes (1)
mirna_target_genes (2)
dmps_per_gene (1,2)
demirs_per_gene (3,4)
methylated_and_mirna_target_genes (1,3)

**Comment by motey** [comment]
Please don't reuse issues.

**Comment by mlazaratos** [comment]
@motey Reopened because it persits.

The refactoring of metaKEGG core is imminent.

**Comment by motey** [comment]
deployed another attempt of a hotfix 🤞

**Comment by motey** [comment]
looks like the new hotfix is working.. will close for now
