### ISSUE TITLE
FetchError: [GET] "/api/single_input_genes/params": 422

### ISSUE THREAD

**Issue by mlazaratos** [DZD-eV-Diabetes-Research/meta-kegg-web-wrapper#11]
when you visit the website, the field under

Step 1: Select an Analysis Method

is blank and below shows 

FetchError: [GET] "/api/single_input_genes/params": 422

It goes away when refreshing or when selecting an Analysis pipeline

**Comment by motey** [comment]
> It goes away when refreshing or when selecting an Analysis pipeline

yep, and it will never come back. there was the old version of the client in your cache. 

(
if it still occurs clear your browser cache for the page. Sometime browsers are very clingy to cached content and its not always comprehensible.
https://superuser.com/questions/278948/clear-cache-for-specific-domain-name-in-chrome
https://superuser.com/questions/173210/how-can-i-clear-a-single-site-from-the-cache-in-firefox
)
